### ISSUE TITLE
Syntax and validity issues.

### ISSUE THREAD

**Issue by Arsadeghi4** [cfpb/hmda-test-files#586]
@MichaelFurey17 

Please see attached spreadsheet of issues.
[Validity Edits Issues.xlsx](https://github.com/cfpb/hmda-test-files/files/2738481/Validity.Edits.Issues.xlsx) 

Thanks,

Amir

**Comment by keileyo** [comment]
@MichaelFurey17 let us know if you have questions about these. 

You can ignore the rows that mention that the edit doesn't exist - those edits were removed from the FIG, so we just don't need test files for the.
