### ISSUE TITLE
Create 2018 and 2019 Parent Directories

### ISSUE THREAD

**Issue by MichaelFurey17** [cfpb/hmda-test-files#662]
Segment the 2018 and 2019 edits by placing code and materials into sub folders. The entire code bases should be separate and distinct from each other but contained in the hmda-test-files repository.

The issue is complete with the following tasks:
- [ ] Create 2018 and 2019 parent directories.

**Comment by Kibrael** [comment]
Can you clarify what you mean by " Add 2018 or 2019 subscripts to each file."?
