### ISSUE TITLE
Refactor file generation scripts, and rename files for 2018 and 2019. 

### ISSUE THREAD

**Issue by MichaelFurey17** [cfpb/hmda-test-files#663]
The issue is complete with the following tasks. 
- [x] Refactor`generate_clean_files.py`to use the FileGenerator class. 
- [x] Refactor `generate_error_files.py` to use the FileGenerator class, and provide the capability for quality files to pass syntax and validity edits.

**Comment by Kibrael** [comment]
This is a good candidate to break into several issues.

One for each refactor, one for each new file, and one for renaming and folder construction.
