### ISSUE TITLE
Provide test files that exercise the race/sex/ethnicity categorization

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-test-files#676]
Create specific test files that test all cases for race/sex/ethnicity assignment according to the FFIEC logic.

This work will result in 3 separate test files:
- [ ] race categorization test file
- [ ] ethnicity categorization test file
- [ ] sex categorization test file

Each file should be accompanied by an answer key that lists the count of records in each category.
- [ ] race categorization answer key
- [ ] sex categorization answer key
- [ ] ethnicity categorization answer key

If this code requires out of pattern work, separate it into a sub folder named "demographic_categorization" and make a separate .py file that generates the test file for each of the race, sex, and ethnicity fields.

This is likely out of pattern work due to the answer key requirement as the regular code allows the user to specify the number of lines in a file and this may be complicated to match to an answer key.

**Comment by MichaelFurey17** [comment]
I think we can include a demographic_categorization py file that would take in an existing test file and produce answer keys based on FFIEC race categorization, ethnicity categorization, and sex categorization logic. We may need to merge a PR for #659 which might make it easier to create custom files that pass syntax and validity edits. I think I will prioritize the demographic categorization file first.
