### ISSUE TITLE
error on v696_3 rules engine. 

### ISSUE THREAD

**Issue by MichaelFurey17** [cfpb/hmda-test-files#714]
According to the logs, clean file generation is stalling on edit v696_3. I believe it has to do with the exemption code included below. 

line 2419 : `vals_2 = ("1111", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",  "16", "17", "18", "19", "20", "21", "22", "23", "24")`

Removing the exemption code allows the file to generate, but this may merit further discussion.

**Comment by Kibrael** [comment]
@MichaelFurey17 v696_3 should only be checking that the populated AUS fields also have populated AUS results and vise versa.

You may want to check alignment on the exemption codes for AUS1 and AUS result1 as this is a hard constraint.
